### PR TITLE
Switches from yarn to pnpm in the frontend ecosystem.

### PR DESCRIPTION
**Pull request by wilkie**
Replaces `yarn` with `pnpm` in the `/frontend` path.

Since this removed the existing `yarn.lock` this has the effect of updating the library versions of essentially all libraries in the project. So, there are a few slight updates to handle massaging out the issues this created which was less trouble than manually getting the `pnpm-lock.yaml` to match the `yarn.lock`.

One of those libraries was `react-player`, which was complicated enough that I moved updates to get us on to the latest there to its own [PR](https://github.com/code-dot-org/code-dot-org/pull/69664). #69664 

## Motivation

We have historically used `yarn` since it was the best tool for its time. In the `/frontend` path, we have a turborepo-powered modular monorepo. `pnpm` is very well-suited for this type of package organization and offers very capable and quick package management that reduces the storage footprint across all of the packages and is likely quicker to invoke. Also, it mirrors `npm` symantics, which makes it easier to understand when seeing `npm` commands and not having to convert them to their `yarn` equivalents. `yarn` semantics for most day-to-day operations largely transfer over just fine. `yarn dev` becomes `pnpm dev`, etc.

I have found this article helpful: https://refine.dev/blog/pnpm-vs-npm-and-yarn

## Testing

`pnpm release:dryrun` passed successfully locally.

## Experimentation

Here is a simple exploration of the file storage needs for `yarn` vs `pnpm` on our so-far simple frontend ecosystem. I cleared out all `node_modules` and then run the install process from a fresh start and measured the resulting `node_modules` directories that are within the different packages.

`pnpm` deduplicates and resolves inner-package `node_modules` with hard links to a central store. It also versions them so that packages can have some level of version drift, although we can discourage that with version linting. That is, you might expect that the root `node_modules`, which contains, like `yarn`, all packages, might be larger, but it is smaller. Also, `pnpm` successfully minimizes all package-level `node_modules` stores to all under 300K. `yarn` fails to truncate the `component-library` package, which is telling as this is the only substantial package. We can expect other packages to meet or exceed this normally.

**Before:**

```
~/code-dot-org/frontend$ yarn workspaces foreach -A exec --  du -sh node_modules
[... some output truncated ...]
[@code-dot-org/frontend]: 1.4G  node_modules
[@code-dot-org/design-system-storybook]: 14M    node_modules
[@code-dot-org/studio]: 72M     node_modules
[@code-dot-org/changelogs]: 4.0K        node_modules
[@code-dot-org/component-library]: 56M  node_modules
[@code-dot-org/component-library-styles]: 4.0K  node_modules
[@code-dot-org/fonts]: 6.0M     node_modules
[@code-dot-org/lint-config]: 4.0K       node_modules
```

**After:**
```
~/code-dot-org/frontend$ pnpm prune
Lockfile is up to date, resolution step is skipped
Already up to date
~/code-dot-org/frontend$ du -sh node_modules && pnpm -r exec du -sh node_modules
1.2G    node_modules
8.0K    node_modules
16K     node_modules
88K     node_modules
192K    node_modules
276K    node_modules
224K    node_modules
120K    node_modules
```

This seems like a 350M difference siding with `pnpm`. Though `pnpm` does keep its own package cache that I'm not measuring against the equivalent `yarn` ecosystem. (Installing from a `clean:deps` is very quick... presumably because it has stored everything in a user cache somewhere)

## PR Creation Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy impacts have been documented
- [ ] Security impacts have been documented
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

File: frontend/apps/studio/tsconfig.app.json [hunk 1]
```diff
@@ -1,6 +1,7 @@
 {
   "extends": "@code-dot-org/lint-config/typescript/tsconfig.vite.app.json",
   "compilerOptions": {
+    "types": ["vite/client"],
```
Comment (stephenliang) [inline frontend/apps/studio/tsconfig.app.json]: This should already be there: https://github.com/code-dot-org/code-dot-org/blob/staging-next/frontend/packages/lint-config/typescript/tsconfig.vite.app.json#L9

Is it not working?

File: frontend/packages/component-library/package.json [hunk 2]
```diff
@@ -108,6 +110,103 @@
...
+      "require": "./dist/cjs/cms/tabGroup/index.js"
+    },
+    "./cms/testimonial": {
+      "types": {
+        "import": "./dist/esm/cms/testimonial/index.d.ts",
+        "require": "./dist/cjs/cms/testimonial/index.d.ts"
+      },
+      "import": "./dist/esm/cms/testimonial/index.mjs",
+      "require": "./dist/cjs/cms/testimonial/index.js"
+    },
```
Comment (stephenliang) [inline frontend/packages/component-library/package.json]: Merge conflict? These were removed

File: frontend/packages/component-library/package.json [hunk 3]
```diff
@@ -414,11 +513,13 @@
     "@code-dot-org/fonts": "workspace:*",
     "@code-dot-org/lint-config": "workspace:*",
     "@release-it/conventional-changelog": "^10.0.0",
+    "@storybook/react-webpack5": "^9.0.18",
```
Comment (stephenliang) [inline frontend/packages/component-library/package.json]: Pretty sure these 3 do not need to be added here as they are in the `design-system-storybook`?

File: frontend/packages/component-library/package.json [hunk 4]
```diff
@@ -414,11 +513,13 @@
...
     "@swc/core": "^1.9.3",
     "@swc/jest": "^0.2.37",
     "@testing-library/dom": "^10.4.0",
     "@testing-library/jest-dom": "^6.6.3",
     "@testing-library/react": "^16.0.1",
+    "@testing-library/user-event": "^14.6.1",
```
Comment (stephenliang) [inline frontend/packages/component-library/package.json]: Pretty sure these 3 do not need to be added here as they are in the `design-system-storybook`?

File: frontend/packages/component-library/package.json [hunk 5]
```diff
@@ -443,6 +544,7 @@
     "rimraf": "^6.0.1",
     "schema-dts": "^1.1.5",
     "shadow-dom-testing-library": "^1.13.1",
+    "storybook": "^9.0.18",
```
Comment (stephenliang) [inline frontend/packages/component-library/package.json]: Pretty sure these 3 do not need to be added here as they are in the `design-system-storybook`?

File: frontend/packages/component-library/package.json (hunk 2 above)
Comment (wilkie) [reply frontend/packages/component-library/package.json]: Yep... bad merge. Dealing with that.

File: frontend/packages/component-library/package.json (hunk 4 above)
Comment (wilkie) [reply frontend/packages/component-library/package.json]:
```
src/tooltip/__tests__/Tooltip.test.tsx:2:23 - error TS2307: Cannot find module '@testing-library/user-event' or its corresponding type declarations.

2 import userEvent from '@testing-library/user-event';
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Comment (stephenliang) [reply frontend/packages/component-library/package.json]: Ah gotcha!

File: frontend/packages/component-library/package.json (hunk 5 above)
Comment (wilkie) [reply frontend/packages/component-library/package.json]: Typechecking the stories requires we add the storybook package to the component-library.

```
src/video/stories/Video.story.tsx:3:41 - error TS2307: Cannot find module 'storybook/test' or its corresponding type declarations.

3 import {within, expect, userEvent} from 'storybook/test';
                                          ~~~~~~~~~~~~~~~~
```

File: frontend/packages/component-library/package.json (hunk 3 above)
Comment (wilkie) [reply frontend/packages/component-library/package.json]:
```
src/typography/stories/Typography.story.tsx:1:35 - error TS2307: Cannot find module '@storybook/react-webpack5' or its corresponding type declarations.

1 import type {Meta, StoryObj} from '@storybook/react-webpack5';
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Comment (stephenliang) [reply frontend/packages/component-library/package.json]: Makes sense. We moved stories to `apps/marketing-storybook` to avoid storybook polluting the package dependency tree but unfortunately didn't apply that pattern here. OK to leave for now.
