### PR TITLE
Rollback level group issue

### PR DESCRIPTION
**Pull request by dmcavoy**
`db_query_test.rb` was failing for `test_script_level_show` in https://github.com/code-dot-org/code-dot-org/pull/36298.  This was because of nil values for parts of the `level_group` model. 

Example:

```
> undefined method `length' for nil:NilClass
app/models/levels/level_group.rb, line 113
------------------------------------------
``` ruby
  108       @pages = properties['levels_and_texts_per_page'].map.with_index do |page_size, page_index|
  109         page_number = page_index + 1
  110         levels_and_texts = all_levels_and_texts[levels_and_texts_offset..(levels_and_texts_offset + page_size - 1)]
  111         page_object = LevelGroupPage.new(page_number, levels_and_texts_offset, levels_and_texts, levels_offset)
  112         levels_and_texts_offset += page_size
> 113         levels_offset += page_object.levels.length if page_object
  114         page_object
  115       end
  116     end
  117   
  118     def self.setup(data)
App backtrace
-------------
 - app/models/levels/level_group.rb:113:in `block in pages'
 - app/models/levels/level_group.rb:108:in `pages'
 - app/models/script_level.rb:403:in `summarize_extra_puzzle_pages'
 - app/models/lesson.rb:230:in `block in summarize'
 - app/models/lesson.rb:201:in `summarize'
 - app/models/lesson_group.rb:148:in `block in summarize'
 - app/models/lesson_group.rb:148:in `summarize'
 - app/views/layouts/_header.html.haml:116:in `_app_views_layouts__header_html_haml__3530793015255366934_70249878386600'
 - app/views/layouts/application.html.haml:61:in `_app_views_layouts_application_html_haml__4534971806343044391_70250065267380'
 - app/controllers/script_levels_controller.rb:498:in `present_level'
 - app/controllers/script_levels_controller.rb:154:in `show'
 - app/controllers/application_controller.rb:167:in `block in with_locale'
 - app/controllers/application_controller.rb:166:in `with_locale'
 - app/helpers/read_replica_helper.rb:20:in `set_read_only_connection_for_block'
 - test/integration/db_query_test.rb:24:in `block (2 levels) in <class:DBQueryTest>'
 - test/testing/capture_queries.rb:65:in `block in capture_queries'
 - test/testing/capture_queries.rb:64:in `capture_queries'
 - test/testing/capture_queries.rb:28:in `assert_queries'
 - test/testing/capture_queries.rb:34:in `block in assert_cached_queries'
 - test/testing/capture_queries.rb:33:in `assert_cached_queries'
 - test/integration/db_query_test.rb:23:in `block in <class:DBQueryTest>'
 - test/testing/setup_all_and_teardown_all.rb:22:in `run'
```

I made some changes to deal with the nil values in this commit https://github.com/code-dot-org/code-dot-org/pull/36298/commits/d67fbc21b47778633ac9a148d681c1fe7b826b6e but then when Dave pointed out some concerned I realized I was not actually using the code path causing the issue  (where lesson_groups summarize method was calling lessons summarize method) and instead could remove it and the changes.  This PR does that.

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
Thank you Dani!
